from fastapi import APIRouter, HTTPException, Request
from src.agents.skill_builder import skill_builder
from src.skills.skill_indexer import skill_indexer
import os

from apps.api.response_models import SuccessResponse

router = APIRouter()

@router.post("/interview", response_model=SuccessResponse)
async def forge_interview(request: Request):
    body = await request.json()
    prompt = body.get("prompt")
    history = body.get("history", [])
    current_preview = body.get("current_preview", {})
    
    data = await skill_builder.interview_step(prompt, history, current_preview)
    return SuccessResponse(data=data)

@router.post("/validate_field", response_model=SuccessResponse)
async def forge_validate_field(request: Request):
    body = await request.json()
    field = body.get("field")
    value = body.get("value")
    # Basic validation logic from v1
    is_valid = len(str(value)) > 0
    return SuccessResponse(data={"is_valid": is_valid})

@router.post("/assemble", response_model=SuccessResponse)
async def forge_assemble(request: Request):
    """Automated Assembly: Write finalized skill to the sandbox and index in Qdrant."""
    body = await request.json()
    preview = body.get("preview", {})
    
    skill_name = preview.get("name", "untitled_skill").lower().replace(" ", "_")
    skill_type = preview.get("type", "Skill")
    subtype = preview.get("subtype", "skill")
    architecture = preview.get("architecture", "")
    
    sandbox_path = os.path.abspath("sandbox")
    os.makedirs(sandbox_path, exist_ok=True)
    
    # 1. Write the .py file
    py_path = os.path.join(sandbox_path, f"{skill_name}.py")
    with open(py_path, "w", encoding="utf-8") as f:
        f.write(f"\"\"\"\nGenerated by The Skill Forge\nType: {skill_type}\n\"\"\"\n\n")
        f.write(architecture)
        
    # 2. Write the .md reference doc
    md_path = os.path.join(sandbox_path, f"{skill_name}.md")
    md_content = f"# {preview.get('name', skill_name)}\n\n"
    md_content += f"**Type:** {skill_type}\n\n"
    md_content += f"{preview.get('description', '')}\n\n"
    
    if preview.get("methods"):
        md_content += "## Methods\n"
        md_content += f"{preview.get('methods')}\n\n"
        
    if preview.get("docs_links"):
        md_content += "## Reference Links\n"
        for link in preview.get("docs_links"):
            md_content += f"- [{link.get('label')}]({link.get('url')})\n"
        md_content += "\n"
        
    with open(md_path, "w", encoding="utf-8") as f:
        f.write(md_content)
        
    # 3. Index in Qdrant
    # Parse methods if it's a string from the frontend
    methods_data = []
    if isinstance(preview.get("methods"), str):
        for line in preview["methods"].split("\n"):
            if " — " in line:
                m_part, m_doc = line.split(" — ", 1)
                m_name = m_part.split("(")[0].strip()
                methods_data.append({"name": m_name, "doc": m_doc})
    
    index_data = {
        "name": preview.get("name", skill_name),
        "description": preview.get("description", ""),
        "subtype": subtype,
        "filename": f"{skill_name}.py",
        "methods": methods_data,
        "docs_links": preview.get("docs_links", []),
        "sample_calls": preview.get("sample_calls", [])
    }
    
    from src.skills.skill_indexer import skill_indexer
    skill_indexer.index(index_data)
    return SuccessResponse(data={"status": "assembled", "filename": f"{skill_name}.py"})
